# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on: 
  push:
    branches:
      - docker-remote
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: brotoo25/notion-currency-docker:latest
  build:
    needs: "push_to_registry"
    name: Running comands on Linode
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        NOTION_DEFAULT_CURRENCY: ${{ secrets.NOTION_DEFAULT_CURRENCY }}
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USERNAME }}
        password: ${{ secrets.LINODE_PASSWORD }}
        port: ${{ secrets.LINODE_PORT }}
        envs: NOTION_TOKEN,NOTION_DATABASE_ID,NOTION_DEFAULT_CURRENCY
        script: bash updateapp.sh $NOTION_TOKEN $NOTION_DATABASE_ID $NOTION_DEFAULT_CURRENCY
          